#!/usr/bin/env python3
"""
ZeroClaw Baby Planner Email Integration
Sends daily baby plans via Gmail SMTP
"""

import smtplib
import ssl
import json
import os
import sys
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path

class BabyPlanEmailer:
    def __init__(self):
        self.config_file = Path.home() / "daily-plans" / "email_config.json"
        self.plan_dir = Path.home() / "daily-plans"
        
    def load_config(self):
        """Load email configuration"""
        if self.config_file.exists():
            with open(self.config_file, 'r') as f:
                return json.load(f)
        return None
    
    def setup_config(self):
        """Interactive setup for email configuration"""
        print("📧 Gmail Email Setup for Baby Plans")
        print("=====================================")
        print("")
        print("To send emails via Gmail, you'll need:")
        print("1. A Gmail address")
        print("2. An App Password (not your regular password)")
        print("   Get one at: https://myaccount.google.com/apppasswords")
        print("")
        
        config = {
            "sender_email": input("Your Gmail address: ").strip(),
            "app_password": input("Gmail App Password: ").strip(),
            "recipient_email": input("Recipient email (where to send plans): ").strip()
        }
        
        # Test the configuration
        print("")
        print("Testing email configuration...")
        if self.test_email_config(config):
            # Save configuration
            with open(self.config_file, 'w') as f:
                json.dump(config, f, indent=2)
            print("✅ Configuration saved successfully!")
            return True
        else:
            print("❌ Configuration test failed. Please check your settings.")
            return False
    
    def test_email_config(self, config):
        """Test email configuration"""
        try:
            # Create test message
            msg = MIMEMultipart()
            msg['From'] = config['sender_email']
            msg['To'] = config['recipient_email']
            msg['Subject'] = "🧪 ZeroClaw Baby Planner - Test Email"
            
            body = """
This is a test email from your ZeroClaw Baby Daily Planning System.

If you receive this, your email configuration is working correctly!

👶 Baby Daily Planner
"""
            msg.attach(MIMEText(body, 'plain'))
            
            # Send email
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
                server.login(config['sender_email'], config['app_password'])
                server.send_message(msg)
            
            return True
        except Exception as e:
            print(f"Error: {e}")
            return False
    
    def send_plan_email(self, date, plan_content):
        """Send daily baby plan via email"""
        config = self.load_config()
        if not config:
            print("❌ Email not configured. Run setup first.")
            return False
        
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = config['sender_email']
            msg['To'] = config['recipient_email']
            msg['Subject'] = f"👶 Baby Daily Plan - {date}"
            
            # Create email body
            email_body = f"""
👶 ZeroClaw Baby Daily Plan - {date}
==========================================

{plan_content}

---
Generated by ZeroClaw Baby Daily Planning System
📍 Server: agent1@10.0.0.231
🤖 AI-Powered Baby Activity Planning
"""
            
            msg.attach(MIMEText(email_body, 'plain'))
            
            # Send email
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
                server.login(config['sender_email'], config['app_password'])
                server.send_message(msg)
            
            print(f"✅ Baby plan for {date} sent to {config['recipient_email']}")
            return True
            
        except Exception as e:
            print(f"❌ Failed to send email: {e}")
            return False
    
    def send_feedback_reminder(self, date):
        """Send reminder to add feedback"""
        config = self.load_config()
        if not config:
            return False
        
        try:
            msg = MIMEMultipart()
            msg['From'] = config['sender_email']
            msg['To'] = config['recipient_email']
            msg['Subject'] = f"📝 Reminder: Add Baby Feedback for {date}"
            
            body = f"""
📝 Baby Plan Feedback Reminder - {date}
=====================================

Don't forget to add feedback about today's baby activities!

Quick add feedback:
ssh agent1@10.0.0.231 "cd /home/agent1/daily-plans && ./daily-planner.sh feedback {date}"

Or use the remote manager:
./baby-planner-remote.sh feedback {date}

What to track:
✅ What baby enjoyed most
❌ What baby didn't like  
🎓 Sleep & feeding patterns
📝 Developmental observations

Your feedback helps the AI learn and improve tomorrow's plan!

👶 ZeroClaw Baby Daily Planner
"""
            
            msg.attach(MIMEText(body, 'plain'))
            
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
                server.login(config['sender_email'], config['app_password'])
                server.send_message(msg)
            
            print(f"✅ Feedback reminder sent for {date}")
            return True
            
        except Exception as e:
            print(f"❌ Failed to send reminder: {e}")
            return False

def main():
    emailer = BabyPlanEmailer()
    
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python3 email_integration.py setup                    # Setup email configuration")
        print("  python3 email_integration.py send <date>              # Send plan for date")
        print("  python3 email_integration.py reminder <date>         # Send feedback reminder")
        print("  python3 email_integration.py test                     # Test email configuration")
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "setup":
        emailer.setup_config()
    
    elif command == "send":
        if len(sys.argv) < 3:
            print("Please provide a date: YYYY-MM-DD")
            sys.exit(1)
        
        date = sys.argv[2]
        plan_file = emailer.plan_dir / f"{date}-plan.md"
        
        if not plan_file.exists():
            print(f"No plan found for {date}")
            sys.exit(1)
        
        with open(plan_file, 'r') as f:
            plan_content = f.read()
        
        emailer.send_plan_email(date, plan_content)
    
    elif command == "reminder":
        if len(sys.argv) < 3:
            print("Please provide a date: YYYY-MM-DD")
            sys.exit(1)
        
        date = sys.argv[2]
        emailer.send_feedback_reminder(date)
    
    elif command == "test":
        config = emailer.load_config()
        if config:
            if emailer.test_email_config(config):
                print("✅ Email configuration test passed!")
            else:
                print("❌ Email configuration test failed!")
        else:
            print("❌ No email configuration found. Run setup first.")
    
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)

if __name__ == "__main__":
    main()
